// USER : SIGNUP
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// USER : LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// USER : LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// USER : LOAD USER
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// POST : GET ALL POST
export const POST_GET_ALL_REQUEST = "POST_GET_ALL_REQUEST";
export const POST_GET_ALL_SUCCESS = "POST_GET_ALL_SUCCESS";
export const POST_GET_ALL_FAILURE = "POST_GET_ALL_FAILURE";

// POST : GET ONE POST
export const POST_GET_DETAIL_REQUEST = "POST_GET_DETAIL_REQUEST";
export const POST_GET_DETAIL_SUCCESS = "POST_GET_DETAIL_SUCCESS";
export const POST_GET_DETAIL_FAILURE = "POST_GET_DETAIL_FAILURE";


// POST : POST SAVE
export const POST_SAVE_REQUEST = "POST_SAVE_REQUEST";
export const POST_SAVE_SUCCESS = "POST_SAVE_SUCCESS";
export const POST_SAVE_FAILURE = "POST_SAVE_FAILURE";

// POST : POST DELETE
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";

// FILE : S3 UPLOAD
export const S3_UPLOAD_REQUEST = "S3_UPLOAD_REQUEST";
export const S3_UPLOAD_SUCCESS = "S3_UPLOAD_SUCCESS";
export const S3_UPLOAD_FAILURE = "S3_UPLOAD_FAILURE";

// ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";
