// USER : SIGNUP
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// USER : LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// USER : LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// USER : LOAD USER
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// POST : GET POST
export const POST_GET_ALL_REQUEST = "POST_GET_ALL_REQUEST";
export const POST_GET_ALL_SUCCESS = "POST_GET_ALL_SUCCESS";
export const POST_GET_ALL_FAILURE = "POST_GET_ALL_FAILURE";

// POST : POST SAVE
export const POST_SAVE_REQUEST = "POST_SAVE_REQUEST";
export const POST_SAVE_SUCCESS = "POST_SAVE_SUCCESS";
export const POST_SAVE_FAILURE = "POST_SAVE_FAILURE";

// ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";
